echo "Welcome to Koridor Cloud"
echo "todays date is: `date`"
echo "To be a devOps engineer you have to put in your best and give in your best"
echo "Good Morning"
echo "Today was not a bad day"
echo "This is my first git pull request"
